spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog202304?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 11111111

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
    root: info
    com.yao: debug
  file: log/blog-dev.log